name: CAO_GUIaddon
author: CasieBarie
version: 1.0
description: GUI Addon for CasieAttractionOperate!
main: me.casiebarie.cao_guiaddon.Main
api-version: 1.13
depend: [CasieAttractionOperate]
softdepend: [PlaceholderAPI]

commands:
  CAOmenu:
    description: Base command of CAOMenuAddon.

permissions:
   CAO.menu.*:
      description: Gives permission to all commands.
      children:
         CAO.menu.use: true
         CAO.menu.admin: true
         CAO.menu.cmd: true
   CAO.menu.use:
      description: Gives permission to use the menu.
      default: op
   CAO.menu.cmd:
      description: Gives permission to the CAOmenu command.
   CAO.menu.admin:
      description: Gives permission to the CAOmenuAdmin command.
      default: op